version: '3.8'

services:
  app:
    build: .
    container_name: goserver
    ports:
      - "8080:8888"
    depends_on:
      - db
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: lorenzomagnano
      DB_PASSWORD: admin
      DB_NAME: provadb
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: provadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network: 

volumes:
  postgres_data: